---
title: AuChimiste Tutorial
author: Walter Dal'Maz Silva
date: today
execute:
  cache: true
  echo: false
format:
  html:
    theme: default
  typst:
    margin: {x: 2.5cm, top: 3.0cm, bottom: 2.0cm}
    logo:
      path: _assets/logo.svg
      width: 5cm
      location: right top
      padding: 10mm
    fontsize: 12pt
    linestretch: 1.25
    fig-format: png
    fig-dpi: 300
engine: julia
execute-dir: file
julia:
  project: ./julia-shared/
  exeflags: ["--project=./julia-shared/"]
---

Let's start by a global import; everything that is intended to be accessible to the end user is found here:

```{julia}
#| echo: true
using Pkg
open("pkg_init.log", "w") do log
    Pkg.activate(joinpath(@__DIR__, "julia-shared"); io=log)
end

push!(LOAD_PATH, joinpath(@__DIR__, "scripts"))
import AuChimiste as AC
```

## Elements database

A built-in elements database is provided by `ChemicalElements`, which is the base building block of `AuChimiste`. It is an extremely simple module and below we go through the whole of its exposed functionalities in just a few lines of code

::: {.callout-note title="Database extent"}
In general you only need to worry about using `ChemicalElements` directly if your calculations require isotopes to be added. The default table of elements provides access only to stable elements.
:::

You can get a list of available atomic symbols with [`list_elements`](@ref). Suppose you want to check if deuterium *D* is present in the list, you can use its [symbol](https://docs.julialang.org/en/v1/base/base/#Core.Symbol) for inspection:

```{julia}
:D ∈ AC.list_elements()
```

Since it is not present but your calculations require this isotope, you feed the database with `add_element`; you also decide to add tritium. In fact `add_element` will not fail if the element exists, but issue a warning. You can try adding an existing element to see what happens:

```{julia}
AC.add_element("D", "deuterium", 1, 2.0141017781)
AC.add_element("Tr", "tritium", 1, 3.0160492820)
AC.add_element("H", "hydrogen", 1, 1.008)
```

If you wish to get back to the standard data you can do so with `reset_elements_table`. Notice below that deuterium mass is no longer available.

```{julia}
AC.reset_elements_table()
AC.has_element(:D)
```

## Element data retrieval

It is possible to retrieve the `atomic_mass`. Other data retrieval functions include `atomic_number` and `element_name`. All of these work with both string and symbols.

```{julia}
AC.atomic_mass(:C), AC.atomic_number(:C), AC.element_name(:C)
```

Getting the whole `element` data can be achieved at once as follows:

```{julia}
AC.element(:Cl)
```

In this case is also possible to query the data through the atomic number:

```{julia}
AC.element(26)
```

On the other hand atomic masses of unstable elements are not accessible:

```{julia}
try AC.atomic_mass(:Po) catch e; @error(e) end
```

To have an unstable element listed, you need to [`add_isotope`](@ref) before. For instance, let's add [Po-187](https://en.wikipedia.org/wiki/Isotopes_of_polonium) to the database.

```{julia}
AC.add_isotope(:Po, 187.003030)
```

## Creating components

Component creation is a trivial task with `AuChimiste`. All you need to do is call `component` with one of the available composition specification methods and a list of keyword arguments representing the element amounts to use. For instance, to create aluminum oxide from its stoichiometry one does:

```{julia}
A = AC.component(:stoichiometry; Al=2, O=3)
```

The above is a syntactic sugar to providing a [`stoichiometry`](@ref) as argument. Please notice that this form requires the overall charge of the component to be specified.

```{julia}
A = component(stoichiometry(Al=2, O=3), 0)
```

The other composition specification methods are `mass_proportions` and `mole_proportions`. Let' s see their use in a more elaborate example with naphthalene ``C_{10}H_{8}``:

```{julia}
naphtalene = AC.component(:stoichiometry; C=10, H=8)
```

So far nothing new. We can use `mass_fractions_map` and `mole_fractions_map` to retrieve the named-tuples of compositions in the units provided by these functions:

```{julia}
Y = AC.mass_fractions_map(naphtalene)
X = AC.mole_fractions_map(naphtalene)
Y, X
```

Using the mass fractions `Y` one can create the equivalent compound from this sort of input. Notice here that a scale is provided to enforce the stoichiometric coefficient of carbon in the species (there is no way to infer it simply from elemental mass fractions).

```{julia}
m_y = AC.component(:mass_proportions; Y..., scale=:C=>10)
```

The same can be done using mole fractions, as follows:

```{julia}
m_x = AC.component(:mole_proportions; X..., scale=:C=>10)
```

If scaling is not provided, the default behavior is enforced, applying unit content to the first element provided in the composition tuple. Notice that these constructors do not sort arguments. This behavior is intended so that compounds can be easily understood by the user in the case a standard formula format exists (as for the oxides above).

```{julia}
component(:mole_proportions; X...)
```

Finally, by *proportions* instead of *fractions* in the name of the composition specification methods we mean that internal normalization is performed. That might be useful, for instance, for reverse-engineering a compound formula from an analysis report.

Often in the field of combustion of heavy-fuel oils one is confronted with empirical fuel compositions given in mass percentages. Assume the following composition; playing with the scaling factor an engineer could infer a candidate composition and identify the family of the fuel [@Lawn1987].

```{julia}
AC.component(:mass_proportions; C = 93.2, H = 6.3, O = 0.3, scale=:C=>10)
```

## Combining components

Some algebraic manipulation is also possible with `ChemicalComponent` instances. Let's see a practical case from cement industry, where compositions are often expressed with a jargon that makes use of multiple of component oxides to represent complex phases such as ``C_{12}A_7``.

Below we create a component `C` for calcium oxide (notice that `C` here was chosen as per industry jargon, it has nothing to do with carbon) and create the multiples of the base oxides (using an extension of `Base.:*`) before combining them through addition (again, by extending `Base.:+` operator).

```{julia}
A = AC.component(:stoichiometry; Al=2, O=3)
C = AC.component(:stoichiometry; Ca=1, O=1)

C12A7 = 12C + 7A
```

::: {.callout-warning title="Meaning of operations"}
All operations performed over `ChemicalComponent` instances are defined on stoichiometric coefficients, *i.e.* the scaling provided by multiplication acts directly on those coefficients, while combining will add coefficients for corresponding elements.
:::

Subtraction operation (`Base.:-`) is also possible, but there are many conditions under which it could fail and it was chosen by design that a negative composition should return the mass imbalance instead, *i.e.* what lacks in `A` to be subtracted `C` and still return a valid component.

```{julia}
A = AC.component(:stoichiometry; Al=2, O=3)
C = AC.component(:stoichiometry; Ca=1, O=1)
A - C
```

On the other hand, if the left component has *enough* of what is being subtracted by the right component, then the actual resulting component is returned:

```{julia}
C12A7 - C
```

## Charged components

For the sake of generality, charged components are also supported. This is required so that ions can be considered in reactions. For instance, to create a sodium chloride formula one can proceed as follows:

```{julia}
Na₊ = AC.component(:stoichiometry; charge=+1, Na=1)
Cl₋ = AC.component(:stoichiometry; charge=-1, Cl=1)

NaCl = Na₊ + Cl₋
```

The user must be aware of a few caveats; first, molecular mass is not corrected for the missing/extra electrons. Electron and mass balance are handled separately, as this makes more sense from a physical standpoint. Scaling of a component also scales its charge. This is required for proper balance of chemical equations.

```{julia}
(3Na₊).charge
```

So the formation of calcium hydroxide can be stated as:

```{julia}
Ca₊₂ = AC.component(:stoichiometry; charge=+2, Ca=1)
OH₋ = AC.component(:stoichiometry; charge=-1, O=1, H=1)

Ca₊₂ + 2OH₋
```

## Quantities of matter

An arbitrary amount of matter can be constructed with `quantity`. The resulting `ComponentQuantity` object supports both scaling (multiplication) and additive (summation) operations. A trivial example would be:

```{julia}
3AC.quantity(A, 1.0)
```

::: {.callout-warning title="Meaning of operations"}
On the other hand, operations performed on `ComponentQuantity` entities are scaled by the elemental mass fractions. That is mostly intuitive in the context of application of this structure.
:::

Well, there is nothing special there, the mass was scaled by *three* with no composition change. The next example is maybe more instructive: we mix one mole of `A` with one mole of `C` by providing their molar masses as the mass of each component. This is interesting because one can quickly verify the correctness of the results.

```{julia}
ma = AC.quantity(A, 0.001A.molar_mass)
mc = AC.quantity(C, 0.001C.molar_mass)
ma + mc
```

Because in many situations one may be interested in mixing quantities directly, a wrapper is provided for eliminating the need of and explicit creation of a `component`.

```{julia}
ma = AC.quantity(:stoichiometry, 1.0; Al=2, O=3)
mc = AC.quantity(:stoichiometry, 1.0; Ca=1, O=1)
ma + mc
```

::: {.callout-warning title="Charge operations"}
Operations on electrical charges of quantities of matter are currently not supported. This functionality was initially conceived for balancing macroscopic amounts of matter and may in the future be extended for ionic substances.
:::
